version: '3.8'

services:

  catalogdb:
    image: postgres:16
    container_name: catalogdb
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: CatalogDB
    ports:
      - "5432:5432"
    volumes:
      - catalog_data:/var/lib/postgresql/data

  basketdb:
    image: postgres:16
    container_name: basketdb
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: BasketDB
    ports:
      - "5433:5432"
    volumes:
      - basket_data:/var/lib/postgresql/data


  orderdb:
    image: mcr.microsoft.com/azure-sql-edge
    user: root
    container_name: orderdb    
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "admin123"
    ports:
      - 1433:1433
    volumes:
      - order_data:/var/opt/mssql
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - catalogdb
      - basketdb
        
  redis:
    image: redis:latest
    container_name: redis-server
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--appendonly", "yes" ]

  catalog.api:
    image: catalog.api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    container_name: catalog-api
    ports:
      - "6000:8080"
      - "6060:8081"
    environment:
      - ConnectionStrings__Database=Server=catalogdb;Port=5432;Database=CatalogDB;User Id=admin;Password=admin123;
    depends_on:
      - catalogdb
  
  basket.api:
    image: basket.api
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    container_name: basket-api
    ports:
      - "6001:8080"
      - "6061:8081"
    environment:
      - ConnectionStrings__Redis=redis-server:6379
      - ConnectionStrings__Database=Server=basketdb;Port=5432;Database=BasketDB;User Id=admin;Password=admin123;
      - GrpcSettings__DiscountUrl=discount-grpc:8080
    depends_on:
      - basketdb
      - redis
      - discount.grpc
      
  discount.grpc:
    image: discount.grpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile
    container_name: discount-grpc
    ports:
      - "6002:8080"
      - "6062:8081"
    environment:
      - ConnectionStrings__Database=Data Source=/app/data/discountdb.db
      - Kestrel__EndpointDefaults__Protocols=Http2
    volumes:
      - discount_data:/app/data    


volumes:
  catalog_data:
  basket_data:
  redis_data:
  discount_data:
  order_data: 


